name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]
        node-version: [20.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: install packages
        run: npm install

      - name: Build
        if: runner.os == 'Linux'
        run: npm run build:linux

      - name: Build
        if: runner.os == 'Windows'
        run: npm run build:win

      - name: Build
        if: runner.os == 'macOS'
        run: npm run build:mac

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}