name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]
        node-version: [20.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: install packages
        run: npm install

      - name: Build
        if: runner.os == 'Linux'
        run: npm run build:linux

      - name: Build
        if: runner.os == 'Windows'
        run: npm run build:win

      - name: Build
        if: runner.os == 'macOS'
        run: npm run build:mac

      - uses: actions/upload-artifact@v3
        with:
          name: YesPlayMusic-mac
          path: dist_electron/*.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: YesPlayMusic-win
          path: dist/*.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: YesPlayMusic-linux
          path: dist_electron/*.AppImage
          if-no-files-found: ignore